name: vida_a_dois
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  connectivity_plus: ^6.0.3
  logger: ^2.4.0
  intl: ^0.19.0
  animated_text_kit: ^4.2.2
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  google_nav_bar: ^5.0.6
  google_fonts: ^6.2.1
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  firebase_auth_mocks: ^0.14.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  build_runner: ^2.4.12
  fake_cloud_firestore: ^3.0.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/signin-assets/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
